"""Explicit legacy window API routes to controller methods and owned state.

New implementation code addresses its feature controller directly. These
properties and wrappers preserve source integrations without storing duplicate
window state. Override a controller method to customize its internal workflows.
"""

from __future__ import annotations

import inspect

from .annotations_editor import AnnotationController
from .canvas_interaction import CanvasInteractionController
from .figure_editor import FigureController
from .legend_editor import LegendController
from .preview_controller import PreviewController
from .project_files import ProjectFilesController
from .project_tree import ProjectTreeController
from .series_editor import SeriesController
from .style_controller import StyleController
from .table_editor import TableEditor
from .window_layout import WindowLayout
from .workspace_controller import WorkspaceController

CONTROLLER_TYPES = {
    "ui_builder": WindowLayout,
    "files": ProjectFilesController,
    "workspace": WorkspaceController,
    "project_tree": ProjectTreeController,
    "table_editor": TableEditor,
    "series_editor": SeriesController,
    "figure_editor": FigureController,
    "annotations_editor": AnnotationController,
    "styles": StyleController,
    "preview": PreviewController,
    "interaction": CanvasInteractionController,
    "legend_editor": LegendController,
}

METHOD_ROUTES = {
    "_build_menus": "ui_builder._build_menus",
    "_add_menu_action": "ui_builder._add_menu_action",
    "_build_ui": "ui_builder._build_ui",
    "_build_data_panel": "ui_builder._build_data_panel",
    "_build_plot_panel": "ui_builder._build_plot_panel",
    "_build_settings_panel": "ui_builder._build_settings_panel",
    "_build_column_box": "ui_builder._build_column_box",
    "_build_series_box": "ui_builder._build_series_box",
    "_build_annotation_box": "ui_builder._build_annotation_box",
    "_build_figure_box": "ui_builder._build_figure_box",
    "_build_style_copy_box": "ui_builder._build_style_copy_box",
    "_build_special_chars_box": "ui_builder._build_special_chars_box",
    "_build_special_char_tab": "ui_builder._build_special_char_tab",
    "insert_special_character": "annotations_editor.insert_special_character",
    "insert_special_character_into_table_name": "annotations_editor.insert_special_character_into_table_name",
    "widget_has_ancestor": "annotations_editor.widget_has_ancestor",
    "_build_export_box": "ui_builder._build_export_box",
    "_connect_signals": "ui_builder._connect_signals",
    "recent_files": "files.recent_files",
    "add_recent_file": "files.add_recent_file",
    "_update_recent_menu": "files._update_recent_menu",
    "_clear_recent_files": "files._clear_recent_files",
    "autosave_project": "files.autosave_project",
    "_notify_background_save_finished": "files._notify_background_save_finished",
    "_background_save_finished": "files._background_save_finished",
    "_write_json_atomic": "files._write_json_atomic",
    "_autosave_origin_metadata": "files._autosave_origin_metadata",
    "_remove_autosave": "files._remove_autosave",
    "_autosave_cleanup_paths": "files._autosave_cleanup_paths",
    "_parse_project_revision": "files._parse_project_revision",
    "_session_autosave_pid": "files._session_autosave_pid",
    "_process_is_running": "files._process_is_running",
    "_recovery_candidates": "files._recovery_candidates",
    "_is_recovery_path": "files._is_recovery_path",
    "_unlink_path": "files._unlink_path",
    "_reset_save_writer": "files._reset_save_writer",
    "_discard_autosave_in_background": "files._discard_autosave_in_background",
    "maybe_restore_autosave": "files.maybe_restore_autosave",
    "save_project": "files.save_project",
    "_choose_project_save_path": "files._choose_project_save_path",
    "_save_project_to": "files._save_project_to",
    "new_project": "files.new_project",
    "project_payload": "workspace.project_payload",
    "project_document": "workspace.project_document",
    "write_project": "files.write_project",
    "save_project_as": "files.save_project_as",
    "load_project": "files.load_project",
    "_confirm_project_replacement": "files._confirm_project_replacement",
    "open_project_path": "files.open_project_path",
    "load_payload_into_model": "files.load_payload_into_model",
    "blank_dataframe": "workspace.blank_dataframe",
    "capture_active_graph": "workspace.capture_active_graph",
    "sync_active_sheet_df": "workspace.sync_active_sheet_df",
    "current_workspace_snapshot": "workspace.current_workspace_snapshot",
    "workspace_snapshot_weight": "workspace.workspace_snapshot_weight",
    "_set_modified": "workspace._set_modified",
    "_update_window_title": "workspace._update_window_title",
    "push_current_undo_state": "workspace.push_current_undo_state",
    "push_undo_baseline": "workspace.push_undo_baseline",
    "update_undo_baseline": "workspace.update_undo_baseline",
    "undo_workspace": "workspace.undo_workspace",
    "redo_workspace": "workspace.redo_workspace",
    "_restore_workspace_snapshot": "workspace._restore_workspace_snapshot",
    "_init_blank_project": "workspace._init_blank_project",
    "set_model": "workspace.set_model",
    "_find_node": "project_tree._find_node",
    "_find_parent": "project_tree._find_parent",
    "_first_leaf": "project_tree._first_leaf",
    "active_node": "project_tree.active_node",
    "current_sheet_id": "project_tree.current_sheet_id",
    "_target_folder_for_new": "project_tree._target_folder_for_new",
    "_containing_folder": "project_tree._containing_folder",
    "_sheet_node_for": "project_tree._sheet_node_for",
    "save_active_state": "workspace.save_active_state",
    "load_sheet_into_table": "workspace.load_sheet_into_table",
    "load_graph": "workspace.load_graph",
    "load_node": "workspace.load_node",
    "set_editing_context": "workspace.set_editing_context",
    "refresh_tree": "project_tree.refresh_tree",
    "_node_label": "project_tree._node_label",
    "_add_tree_item": "project_tree._add_tree_item",
    "_on_item_expanded": "project_tree._on_item_expanded",
    "_on_item_collapsed": "project_tree._on_item_collapsed",
    "update_project_move_buttons": "project_tree.update_project_move_buttons",
    "on_tree_selection_changed": "project_tree.on_tree_selection_changed",
    "_select_node": "project_tree._select_node",
    "new_sheet": "project_tree.new_sheet",
    "new_graph": "project_tree.new_graph",
    "new_folder": "project_tree.new_folder",
    "duplicate_selected_node": "project_tree.duplicate_selected_node",
    "_duplicate_node": "project_tree._duplicate_node",
    "_node_name": "project_tree._node_name",
    "_node_name_key": "project_tree._node_name_key",
    "_sibling_name_collision": "project_tree._sibling_name_collision",
    "rename_node": "project_tree.rename_node",
    "rename_selected_node": "project_tree.rename_selected_node",
    "rename_project_root": "project_tree.rename_project_root",
    "_graphs_referencing": "project_tree._graphs_referencing",
    "delete_selected_node": "project_tree.delete_selected_node",
    "_collect_sheet_ids": "project_tree._collect_sheet_ids",
    "_collect_graph_ids": "project_tree._collect_graph_ids",
    "_remove_node_objects": "project_tree._remove_node_objects",
    "_remove_nodes_by_ref": "project_tree._remove_nodes_by_ref",
    "move_selected_node": "project_tree.move_selected_node",
    "show_tree_menu": "project_tree.show_tree_menu",
    "_build_move_menu": "project_tree._build_move_menu",
    "_collect_descendant_ids": "project_tree._collect_descendant_ids",
    "_move_node_to_folder": "project_tree._move_node_to_folder",
    "handle_tree_drop": "project_tree.handle_tree_drop",
    "_unique_sheet_name": "project_tree._unique_sheet_name",
    "_unique_graph_name": "project_tree._unique_graph_name",
    "_unique_folder_name": "project_tree._unique_folder_name",
    "_unique_name": "project_tree._unique_name",
    "handle_table_paste": "table_editor.handle_table_paste",
    "replace_table_from_text": "table_editor.replace_table_from_text",
    "set_dataframe": "table_editor.set_dataframe",
    "import_data_file": "table_editor.import_data_file",
    "import_data_path": "table_editor.import_data_path",
    "_read_text_file": "table_editor._read_text_file",
    "populate_table": "table_editor.populate_table",
    "populate_columns": "table_editor.populate_columns",
    "handle_table_item_changed": "table_editor.handle_table_item_changed",
    "sync_dataframe_from_table": "table_editor.sync_dataframe_from_table",
    "_select_table_context_target": "table_editor._select_table_context_target",
    "show_table_menu": "table_editor.show_table_menu",
    "add_row": "table_editor.add_row",
    "add_column": "table_editor.add_column",
    "_rename_sheet_column_references": "table_editor._rename_sheet_column_references",
    "_sync_sheet_series_labels": "table_editor._sync_sheet_series_labels",
    "_delete_sheet_column_references": "table_editor._delete_sheet_column_references",
    "_restore_active_graph_column_state": "table_editor._restore_active_graph_column_state",
    "rename_current_column": "table_editor.rename_current_column",
    "set_selected_column_roles": "table_editor.set_selected_column_roles",
    "clear_selected_cells": "table_editor.clear_selected_cells",
    "delete_selected_rows": "table_editor.delete_selected_rows",
    "delete_selected_columns": "table_editor.delete_selected_columns",
    "_selected_columns": "table_editor._selected_columns",
    "_merge_intervals": "table_editor._merge_intervals",
    "_paste_grid": "table_editor._paste_grid",
    "_ensure_table_size": "table_editor._ensure_table_size",
    "sync_dataframe_after_paste": "table_editor.sync_dataframe_after_paste",
    "_table_is_blank": "table_editor._table_is_blank",
    "_header_text": "table_editor._header_text",
    "_next_column_name": "table_editor._next_column_name",
    "_ensure_metadata_rows": "table_editor._ensure_metadata_rows",
    "_column_role": "table_editor._column_role",
    "_nearest_left_x": "table_editor._nearest_left_x",
    "_column_name": "table_editor._column_name",
    "_plot_dataframe": "table_editor._plot_dataframe",
    "_normalize_role_cell": "table_editor._normalize_role_cell",
    "_normalized_role_text": "table_editor._normalized_role_text",
    "_update_column_headers": "table_editor._update_column_headers",
    "_set_checked_y_columns": "table_editor._set_checked_y_columns",
    "checked_y_columns": "table_editor.checked_y_columns",
    "set_all_plot_y_checked": "table_editor.set_all_plot_y_checked",
    "refresh_series_configs": "table_editor.refresh_series_configs",
    "handle_plot_y_changed": "series_editor.handle_plot_y_changed",
    "handle_plot_y_clicked": "series_editor.handle_plot_y_clicked",
    "select_series_for_y_column": "series_editor.select_series_for_y_column",
    "update_style_targets": "series_editor.update_style_targets",
    "handle_style_target_changed": "series_editor.handle_style_target_changed",
    "_load_series_into_widgets": "series_editor._load_series_into_widgets",
    "_refresh_error_column_combo": "series_editor._refresh_error_column_combo",
    "apply_series_widget_state": "series_editor.apply_series_widget_state",
    "choose_series_color": "series_editor.choose_series_color",
    "apply_colormap_to_plotted_series": "series_editor.apply_colormap_to_plotted_series",
    "apply_custom_gradient_to_series": "series_editor.apply_custom_gradient_to_series",
    "_save_custom_gradient": "series_editor._save_custom_gradient",
    "apply_recommended_palette_to_series": "series_editor.apply_recommended_palette_to_series",
    "selected_cmap_columns": "series_editor.selected_cmap_columns",
    "recommended_colors": "series_editor.recommended_colors",
    "_alpha_dist": "series_editor._alpha_dist",
    "refresh_cmap_column_list": "series_editor.refresh_cmap_column_list",
    "_discard_invalid_series_color_recipe": "series_editor._discard_invalid_series_color_recipe",
    "choose_cmap_base_color": "series_editor.choose_cmap_base_color",
    "_set_cmap_base_color_button": "series_editor._set_cmap_base_color_button",
    "update_axis_control_states": "figure_editor.update_axis_control_states",
    "choose_y2_axis_color": "figure_editor.choose_y2_axis_color",
    "choose_y_axis_color": "figure_editor.choose_y_axis_color",
    "_set_y2_axis_color_button": "figure_editor._set_y2_axis_color_button",
    "_set_y_axis_color_button": "figure_editor._set_y_axis_color_button",
    "handle_preset_changed": "figure_editor.handle_preset_changed",
    "handle_plot_ratio_lock_toggled": "figure_editor.handle_plot_ratio_lock_toggled",
    "handle_plot_ratio_preset_changed": "figure_editor.handle_plot_ratio_preset_changed",
    "handle_plot_dimension_changed": "figure_editor.handle_plot_dimension_changed",
    "active_plot_ratio": "figure_editor.active_plot_ratio",
    "current_plot_ratio": "figure_editor.current_plot_ratio",
    "plot_ratio_from_preset": "figure_editor.plot_ratio_from_preset",
    "apply_plot_ratio_from_width": "figure_editor.apply_plot_ratio_from_width",
    "apply_plot_ratio_from_height": "figure_editor.apply_plot_ratio_from_height",
    "collect_plot_config": "figure_editor.collect_plot_config",
    "selected_series_configs": "figure_editor.selected_series_configs",
    "choose_annotation_color": "annotations_editor.choose_annotation_color",
    "add_annotation": "annotations_editor.add_annotation",
    "default_annotation_geometry": "annotations_editor.default_annotation_geometry",
    "_annotation_display_geometry": "annotations_editor._annotation_display_geometry",
    "annotation_axes": "annotations_editor.annotation_axes",
    "current_broken_y_active": "annotations_editor.current_broken_y_active",
    "legend_axes": "annotations_editor.legend_axes",
    "remove_selected_annotation": "annotations_editor.remove_selected_annotation",
    "copy_selected_annotation": "annotations_editor.copy_selected_annotation",
    "paste_annotation": "annotations_editor.paste_annotation",
    "refresh_annotation_list": "annotations_editor.refresh_annotation_list",
    "update_annotation_list_item": "annotations_editor.update_annotation_list_item",
    "selected_annotation_indices": "annotations_editor.selected_annotation_indices",
    "update_selected_annotation": "annotations_editor.update_selected_annotation",
    "_set_annotation_color_button": "annotations_editor._set_annotation_color_button",
    "capture_current_style": "styles.capture_current_style",
    "style_bundle_to_payload": "styles.style_bundle_to_payload",
    "style_bundle_from_payload": "styles.style_bundle_from_payload",
    "saved_style_payloads": "styles.saved_style_payloads",
    "write_saved_style_payloads": "styles.write_saved_style_payloads",
    "refresh_saved_style_combo": "styles.refresh_saved_style_combo",
    "update_named_style_save_button": "styles.update_named_style_save_button",
    "matching_saved_style_name": "styles.matching_saved_style_name",
    "save_named_style": "styles.save_named_style",
    "delete_named_style": "styles.delete_named_style",
    "copy_current_style": "styles.copy_current_style",
    "apply_copied_style": "styles.apply_copied_style",
    "apply_named_style": "styles.apply_named_style",
    "apply_style_bundle": "styles.apply_style_bundle",
    "copy_figure_to_clipboard": "preview.copy_figure_to_clipboard",
    "_render_request": "preview._render_request",
    "_adopt_render_result": "preview._adopt_render_result",
    "schedule_render": "preview.schedule_render",
    "update_linear_fit_result_display": "preview.update_linear_fit_result_display",
    "render_plot": "preview.render_plot",
    "update_render_issues": "preview.update_render_issues",
    "center_plot_box": "preview.center_plot_box",
    "center_content": "preview.center_content",
    "fit_canvas_to_content": "preview.fit_canvas_to_content",
    "figure_content_bbox": "preview.figure_content_bbox",
    "plot_area_bbox": "preview.plot_area_bbox",
    "artist_window_extent": "preview.artist_window_extent",
    "set_canvas_size": "preview.set_canvas_size",
    "set_plot_margins": "preview.set_plot_margins",
    "_replace_canvas": "preview._replace_canvas",
    "update_canvas_size": "preview.update_canvas_size",
    "center_preview": "preview.center_preview",
    "restore_preview_center": "preview.restore_preview_center",
    "export_current_figure": "preview.export_current_figure",
    "_ordered_graphs_with_folder": "preview._ordered_graphs_with_folder",
    "export_all_figures": "preview.export_all_figures",
    "_project_plot_dataframe": "preview._project_plot_dataframe",
    "_project_column_name": "preview._project_column_name",
    "_project_nearest_left_x": "preview._project_nearest_left_x",
    "_project_series_configs": "preview._project_series_configs",
    "_safe_export_filename": "preview._safe_export_filename",
    "_unique_export_path": "preview._unique_export_path",
    "handle_canvas_press": "interaction.handle_canvas_press",
    "annotation_hit_order": "interaction.annotation_hit_order",
    "best_annotation_hit": "interaction.best_annotation_hit",
    "start_plot_box_drag": "interaction.start_plot_box_drag",
    "plot_box_drag_requested": "interaction.plot_box_drag_requested",
    "start_annotation_drag": "interaction.start_annotation_drag",
    "annotation_group_drag_requested": "interaction.annotation_group_drag_requested",
    "select_single_annotation": "interaction.select_single_annotation",
    "start_legend_drag": "interaction.start_legend_drag",
    "edit_legend_text": "legend_editor.edit_legend_text",
    "legend_editor_candidates": "legend_editor.legend_editor_candidates",
    "legend_editor_entries": "legend_editor.legend_editor_entries",
    "apply_legend_entry_config": "legend_editor.apply_legend_entry_config",
    "legend_anchor_axes_fraction": "interaction.legend_anchor_axes_fraction",
    "annotation_hit_distance": "interaction.annotation_hit_distance",
    "annotation_hit_distance_for_point": "interaction.annotation_hit_distance_for_point",
    "text_annotation_hit_distance": "interaction.text_annotation_hit_distance",
    "line_annotation_hit_distance": "interaction.line_annotation_hit_distance",
    "box_annotation_hit_distance": "interaction.box_annotation_hit_distance",
    "circle_annotation_hit_distance": "interaction.circle_annotation_hit_distance",
    "annotation_local_point": "interaction.annotation_local_point",
    "point_to_segment_distance": "interaction.point_to_segment_distance",
    "rectangle_border_distance": "interaction.rectangle_border_distance",
    "annotation_handle_hit_test": "interaction.annotation_handle_hit_test",
    "handle_canvas_motion": "interaction.handle_canvas_motion",
    "_update_hover_hint": "interaction._update_hover_hint",
    "handle_plot_box_motion": "interaction.handle_plot_box_motion",
    "apply_current_plot_box_layout": "interaction.apply_current_plot_box_layout",
    "refresh_annotation_artists": "interaction.refresh_annotation_artists",
    "handle_legend_motion": "interaction.handle_legend_motion",
    "event_to_axes_fraction": "interaction.event_to_axes_fraction",
    "_rotated_endpoint": "interaction._rotated_endpoint",
    "ctrl_is_pressed": "interaction.ctrl_is_pressed",
    "resize_annotation_from_event": "interaction.resize_annotation_from_event",
    "rotate_annotation_from_event": "interaction.rotate_annotation_from_event",
    "update_annotation_artist": "interaction.update_annotation_artist",
    "annotation_handle_points": "interaction.annotation_handle_points",
    "draw_annotation_handles": "interaction.draw_annotation_handles",
    "handle_canvas_scroll": "interaction.handle_canvas_scroll",
    "preview_zoom_delta": "interaction.preview_zoom_delta",
    "handle_canvas_release": "interaction.handle_canvas_release",
    "update_annotation_inputs": "annotations_editor.update_annotation_inputs",
    "_connect_change": "workspace._connect_change",
    "handle_undoable_widget_change": "workspace.handle_undoable_widget_change",
    "handle_figure_setting_changed": "figure_editor.handle_figure_setting_changed",
    "_reset_undo_coalescing": "workspace._reset_undo_coalescing",
    "_seed_blank_sheet": "workspace._seed_blank_sheet",
    "_load_config_into_widgets": "figure_editor._load_config_into_widgets",
    "delete_selected_annotation_from_key": "annotations_editor.delete_selected_annotation_from_key",
    "nudge_selected_annotations_from_key": "interaction.nudge_selected_annotations_from_key",
    "_set_color_button": "series_editor._set_color_button",
    "_remove_legend_sources": "table_editor._remove_legend_sources",
    "_rename_graph_column_reference": "table_editor._rename_graph_column_reference",
    "_delete_graph_column_references": "table_editor._delete_graph_column_references",
    "_int_spin": "ui_builder._int_spin",
}

STATE_ROUTES = {
    "document": "session.document",
    "df": "session.df",
    "plot_config": "session.plot_config",
    "annotations": "session.annotations",
    "series_by_y": "session.series_by_y",
    "sheets": "session.sheets",
    "graphs": "session.graphs",
    "tree_root": "session.tree_root",
    "active_node_id": "session.active_node_id",
    "active_sheet_id": "session.active_sheet_id",
    "active_graph_id": "session.active_graph_id",
    "loading_project_figure": "session.loading_project_figure",
    "_is_modified": "session.modified",
    "restoring_undo": "workspace.restoring_undo",
    "autosave_path": "files.autosave_path",
    "_default_autosave_path": "files._default_autosave_path",
    "legacy_autosave_path": "files.legacy_autosave_path",
    "last_folder": "files.last_folder",
    "current_project_path": "files.current_project_path",
    "_current_project_revision": "files._current_project_revision",
    "_closing": "files._closing",
    "_recovery_source_path": "files._recovery_source_path",
    "_recovery_origin_path": "files._recovery_origin_path",
    "_recovery_origin_revision": "files._recovery_origin_revision",
    "_autosave_futures": "files._autosave_futures",
    "_save_completion_bridge": "files._save_completion_bridge",
    "save_writer": "files.save_writer",
    "autosave_timer": "files.autosave_timer",
    "rendering": "preview.rendering",
    "preview_numeric_cache": "preview.preview_numeric_cache",
    "current_figure": "preview.current_figure",
    "annotation_artists": "preview.annotation_artists",
    "legend_artist": "preview.legend_artist",
    "linear_fit_results_by_y": "preview.linear_fit_results_by_y",
    "render_timer": "preview.render_timer",
    "canvas": "preview.canvas",
    "toolbar": "preview.toolbar",
    "preview_base_width_px": "preview.preview_base_width_px",
    "preview_base_height_px": "preview.preview_base_height_px",
    "preview_figure_width_in": "preview.preview_figure_width_in",
    "preview_figure_height_in": "preview.preview_figure_height_in",
    "annotation_handle_artists": "interaction.annotation_handle_artists",
    "drag_annotation_index": "interaction.drag_annotation_index",
    "dragging_legend": "interaction.dragging_legend",
    "dragging_plot_box": "interaction.dragging_plot_box",
    "drag_legend_start": "interaction.drag_legend_start",
    "drag_legend_original": "interaction.drag_legend_original",
    "drag_plot_start_pixels": "interaction.drag_plot_start_pixels",
    "drag_plot_original_margins": "interaction.drag_plot_original_margins",
    "drag_start": "interaction.drag_start",
    "drag_mode": "interaction.drag_mode",
    "drag_original": "interaction.drag_original",
    "drag_group_original": "interaction.drag_group_original",
    "_hover_hint": "interaction._hover_hint",
    "undo_history": "workspace.undo_history",
    "_tree_items": "project_tree._tree_items",
    "style_clipboard": "styles.style_clipboard",
    "annotation_clipboard": "annotations_editor.annotation_clipboard",
    "special_text_target": "annotations_editor.special_text_target",
    "updating_plot_ratio": "figure_editor.updating_plot_ratio",
}


def _method_forwarder(owner, name):
    def forward(window, *args, **kwargs):
        return getattr(getattr(window, owner), name)(*args, **kwargs)

    forward.__name__ = name
    forward.__qualname__ = f"GraphDrawerWindow.{name}"
    return forward


def _state_property(owner, name):
    def read(window):
        return getattr(getattr(window, owner), name)

    def write(window, value):
        setattr(getattr(window, owner), name, value)

    return property(read, write)


def legacy_window_api(cls):
    for name, path in METHOD_ROUTES.items():
        owner, target = path.split(".", 1)
        controller_type = CONTROLLER_TYPES[owner]
        implementation = inspect.getattr_static(controller_type, target)
        if isinstance(implementation, (staticmethod, classmethod)):
            setattr(cls, name, staticmethod(getattr(controller_type, target)))
        else:
            setattr(cls, name, _method_forwarder(owner, target))
    for name, path in STATE_ROUTES.items():
        owner, target = path.split(".", 1)
        setattr(cls, name, _state_property(owner, target))
    return cls
